
namespace LuiTool.HavokScript.Assembly;

public static class HksOpMetaTable
{
    public static readonly HksOpMeta[] OpMeta =
    {
        new HksOpMeta(HksOpCode.GETFIELD,                   HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.CONST),
        new HksOpMeta(HksOpCode.TEST,                       HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.UNUSED, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.CALL_I,                     HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.CALL_C,                     HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.EQ,                         HksOpMode.ABC,  HksOpArgModeA.NUMBER, HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.EQ_BK,                      HksOpMode.ABC,  HksOpArgModeA.NUMBER, HksOpArgModeB.CONST,  HksOpArgModeC.REG),
        new HksOpMeta(HksOpCode.GETGLOBAL,                  HksOpMode.ABx,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.MOVE,                       HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.SELF,                       HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.RETURN,                     HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.GETTABLE_S,                 HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.GETTABLE_N,                 HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.GETTABLE,                   HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.LOADBOOL,                   HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.TFORLOOP,                   HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.UNUSED, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.SETFIELD,                   HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.SETTABLE_S,                 HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.SETTABLE_S_BK,              HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.SETTABLE_N,                 HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.SETTABLE_N_BK,              HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.SETTABLE,                   HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.SETTABLE_BK,                HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.TAILCALL_I,                 HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.TAILCALL_C,                 HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.TAILCALL_M,                 HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.LOADK,                      HksOpMode.ABx,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.LOADNIL,                    HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.SETGLOBAL,                  HksOpMode.ABx,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.JMP,                        HksOpMode.AsBx, HksOpArgModeA.UNUSED, HksOpArgModeB.OFFSET, HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.CALL_M,                     HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.CALL,                       HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.INTRINSIC_INDEX,            HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.INTRINSIC_NEWINDEX,         HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.INTRINSIC_SELF,             HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.INTRINSIC_LITERAL,          HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.INTRINSIC_NEWINDEX_LITERAL, HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.INTRINSIC_SELF_LITERAL,     HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.TAILCALL,                   HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.GETUPVAL,                   HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.SETUPVAL,                   HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.ADD,                        HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.ADD_BK,                     HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.REG),
        new HksOpMeta(HksOpCode.SUB,                        HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.SUB_BK,                     HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.REG),
        new HksOpMeta(HksOpCode.MUL,                        HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.MUL_BK,                     HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.REG),
        new HksOpMeta(HksOpCode.DIV,                        HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.DIV_BK,                     HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.REG),
        new HksOpMeta(HksOpCode.MOD,                        HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.MOD_BK,                     HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.REG),
        new HksOpMeta(HksOpCode.POW,                        HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.POW_BK,                     HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.REG),
        new HksOpMeta(HksOpCode.NEWTABLE,                   HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.UNM,                        HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.NOT,                        HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.LEN,                        HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.LT,                         HksOpMode.ABC,  HksOpArgModeA.NUMBER, HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.LT_BK,                      HksOpMode.ABC,  HksOpArgModeA.NUMBER, HksOpArgModeB.CONST,  HksOpArgModeC.REG),
        new HksOpMeta(HksOpCode.LE,                         HksOpMode.ABC,  HksOpArgModeA.NUMBER, HksOpArgModeB.REG,    HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.LE_BK,                      HksOpMode.ABC,  HksOpArgModeA.NUMBER, HksOpArgModeB.CONST,  HksOpArgModeC.REG),
        new HksOpMeta(HksOpCode.CONCAT,                     HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.TESTSET,                    HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.FORPREP,                    HksOpMode.AsBx, HksOpArgModeA.REG,    HksOpArgModeB.OFFSET, HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.FORLOOP,                    HksOpMode.AsBx, HksOpArgModeA.REG,    HksOpArgModeB.OFFSET, HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.SETLIST,                    HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.CLOSE,                      HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.UNUSED, HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.CLOSURE,                    HksOpMode.ABx,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.VARARG,                     HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.TAILCALL_I_R1,              HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.CALL_I_R1,                  HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.SETUPVAL_R1,                HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.TEST_R1,                    HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.UNUSED, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.NOT_R1,                     HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.GETFIELD_R1,                HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.CONST),
        new HksOpMeta(HksOpCode.SETFIELD_R1,                HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.NEWSTRUCT,                  HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.DATA,                       HksOpMode.ABx,  HksOpArgModeA.UNUSED, HksOpArgModeB.OFFSET, HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.SETSLOTN,                   HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.UNUSED, HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.SETSLOTI,                   HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.SETSLOT,                    HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.SETSLOTS,                   HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.REG),
        new HksOpMeta(HksOpCode.SETSLOTMT,                  HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.R_OR_K),
        new HksOpMeta(HksOpCode.CHECKTYPE,                  HksOpMode.ABx,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.CHECKTYPES,                 HksOpMode.ABx,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.GETSLOT,                    HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.GETSLOTMT,                  HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.SELFSLOT,                   HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.SELFSLOTMT,                 HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.GETFIELD_MM,                HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.CONST),
        new HksOpMeta(HksOpCode.CHECKTYPE_D,                HksOpMode.ABx,  HksOpArgModeA.REG,    HksOpArgModeB.NUMBER, HksOpArgModeC.UNUSED),
        new HksOpMeta(HksOpCode.GETSLOT_D,                  HksOpMode.ABC,  HksOpArgModeA.REG,    HksOpArgModeB.REG,    HksOpArgModeC.NUMBER),
        new HksOpMeta(HksOpCode.GETGLOBAL_MEM,              HksOpMode.ABx,  HksOpArgModeA.REG,    HksOpArgModeB.CONST,  HksOpArgModeC.UNUSED)
    // DELETE,
    // DELETE_BK,
    };
}
